In [4]:
import numpy as np
a = np.random.rand(1000000000)
b = np.random.rand(1000000000)

import time
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("Vectorized version:"+str(1000*(toc-tic))+"ms")

Vectorized version:15755.407094955444ms


In [9]:
a = np.random.random((3,4))

b = np.random.random((4,1))
print(a)
print(b)
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j]*b[j][0]

print(c)

[[0.44199071 0.74829057 0.33293794 0.65475984]
 [0.62162323 0.78786259 0.45278206 0.24200816]
 [0.76103889 0.5052728  0.34671438 0.7028445 ]]
[[0.96912738]
 [0.98671797]
 [0.76179328]
 [0.3121354 ]]


IndexError: invalid index to scalar variable.